In [9]:
import pandas as pd

In [11]:
data = pd.read_csv('C:\Potenup\Korean-Sign-Language-Project\data\sign_data.csv', header=None)

In [12]:
data

,0,1,2,3,4,5,6,7,8,9,...,97,98,99,100,101,102,103,104,105,106
0,1,0,0,0,0,0,0,0,0,0,...,0.379778,0.562198,0.512174,0.588963,0.364358,0.591782,0.459157,0.679313,0.399459,0.677068
1,1,0,0,0,0,0,0,0,0,0,...,0.379560,0.566029,0.511986,0.591452,0.364665,0.595238,0.459127,0.682513,0.399348,0.679767
2,1,0,0,0,0,0,0,0,0,0,...,0.379548,0.565360,0.511898,0.591293,0.364580,0.594964,0.458903,0.681837,0.399015,0.679187